services:

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

# volumes:
#   backend_static:
#   media_value:
#   db_value:

# # volumes:
# #   postgres_data:
# #   static_value:
# #   media_value:
# #   data_value:

# services:

#   db:
#     image: postgres:13.0-alpine
#     restart: always
#     environment:
#       - POSTGRES_USER=foodgram_user
#       - POSTGRES_PASSWORD=foodgram_password
#       - POSTGRES_DB=postgres
#     volumes:
#       - db_value:/var/lib/postgresql/data/
#     env_file:
#       - ./.env

#   backend:
#     build:
#       context: ../backend
#       dockerfile: Dockerfile
#     image: smolodtsova13/foodgram_backend:latest
#     restart: always
#     command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
#     depends_on:
#       - db
#     volumes:
#       - backend_static:/app/backend_static/
#       - media_value:/app/media/
#     env_file:
#       - ./.env

#   frontend:
#     build:
#       context: ../frontend
#       dockerfile: Dockerfile
#     image: smolodtsova13/foodgram_frontend:latest
#     volumes:
#       - ../frontend/:/app/result_build/
#     depends_on:
#       - backend

#   nginx:
#     image: nginx:1.19.3
#     ports:
#       - 80:80
#      volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ../frontend/build:/usr/share/nginx/html/
#       - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
#       - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
#       - backend_static:/usr/share/nginx/html/backend_static/:ro
#       - media_value:/usr/share/nginx/html/media/:ro
#       # - static_value:/var/html/static/
#       # - media_value:/var/html/media/
#     depends_on:
#       - backend
#       - frontend

