volumes:
  static:
  media_value:
  db_value:

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    # build:
    #   context: ../backend
    #   dockerfile: Dockerfile
    image: smolodtsova13/foodgram_backend:latest
    restart: always
    env_file:
      - ./.env
    # command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media_value:/app/media

  frontend:
    container_name: foodgram_frontend
    image: smolodtsova13/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    depends_on:
      - backend
    volumes:
      - static:/frontend_static
    #  - ../frontend/:/frontend_static/
    # build: ../frontend
  
  nginx:
    image: smolodtsova13/foodgram_nginx:latest
    # build: ../nginx/
    env_file: .env
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media_value:/app/media/
   





