  static:
  media_value:
  db_value:

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: smolodtsova13/foodgram_backend:latest
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media_value:/app/media

  frontend:
    container_name: foodgram_frontend
    image: smolodtsova13/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    depends_on:
      - backend
    volumes:
      - static:/frontend_static
  nginx:
    image: smolodtsova13/foodgram_nginx:latest
    env_file: .env
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"

    volumes:
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media_value:/app/media/
