# Generated by Django 3.2 on 2024-09-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240922_2239'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientrecipe',
            name='unique_ingredient_recipe_combination',
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='volume',
            new_name='amount',
        ),
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe', 'amount'), name='unique_ingredient_recipe_combination'),
        ),
    ]
