# Generated by Django 3.2 on 2024-09-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20240924_0305'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourites',
            name='unique_favorite_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredient',
        ),
        migrations.RemoveConstraint(
            model_name='ingredientrecipe',
            name='unique_ingredient_recipe_combination',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_shopping_list',
        ),
        migrations.RemoveConstraint(
            model_name='tagrecipe',
            name='unique_tag_recipe_combination',
        ),
    ]
