# Generated by Django 3.2 on 2024-09-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_foodgramuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar_default.jpg', null=True, upload_to='users', verbose_name='Аватар профиля'),
        ),
    ]
