# Generated by Django 3.2 on 2024-09-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_foodgramuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatar_default.jpg', null=True, upload_to='users', verbose_name='Аватар профиля'),
        ),
    ]
